### PR TITLE
Add support for PostgreSQL.

### PR DESCRIPTION
**Pull request by m50**
Main Changes:
 - Add grammar files that contain everything necessary for building SQL queries.
 - Set Grammar according to sql dsn.
 - Add pgsql schema

Reason for changes:
 - Postgresql uses "end" as a keyword to end the query, as such the old method kills queries, causing errors.
 - Putting everything in double-quotes prevents the use of keywords causing problems.

### CODE REVIEW

**Comment by msimerson** [comment]
Wow, this is a great PR @m50. Thank you.

In share/mail-dmarc.ini is a commented out example for configuration with MySQL. Adding one there for a typical Postgresql server would be good.

I'm thinking out loud here, about how to defend the new Pgsql support from getting broken. Now that there's more than one grammar, something that seems likely to help avoid future breakage would be exercising each grammar during the CI tests.  We can have Travis spin up a MySQL and PgSQL server by adding this to the .travis.yml file:

```diff
diff --git a/.travis.yml b/.travis.yml
index 181120d..c3a480d 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,6 +6,10 @@ perl:
 # - "5.14"
 # - "5.10"
 
+services:
+  - mysql
+  - postgresql
+
 before_install:
 
 install:
```

Then in `t/12.Report.Store.SQL.t`, attempt to use SQLite, and attempt to connect to MySQL and Pgsql. For any connections that succeed (like on Travis where all 3 should), run the set of tests against all 3 servers. By doing connection tests, we could avoid test failures on developers hosts where they don't have those services available.

That would also fix the decline in test coverage.

**Comment by m50** [comment]
Ok, I will get on that!

Agreed, it would be beneficial to be able to test all the grammars.

**Comment by m50** [comment]
I apologize about the number of commits. I didn't have a proper Perl testing environment for this right away. 

Anyways, all tests are passing, I am not sure why there is still a decrease in coverage, as it's now covering MySQL and Postgresql and not just SQLite.

A quick note: MySQL was failing tests, so I had to implement some fixes for that as well.

**Comment by msimerson** [comment]
> I apologize about the number of commits

No worries, GitHub lets us squash them.

>  I am not sure why there is still a decrease in coverage, as it's now covering MySQL and Postgresql and not just SQLite.

Me neither, but I will merge anyway. The coveralls report appears to also be measuring the coverage of the files in `t/*`, which it shouldn't. I'll poke at that later.

Last items: 

- in the README, add yourself to the `CONTRIBUTORS` section with your preferred email address (or none).
- in lib/Mail/DMARC, this line needs to be updated: `The Store class includes a SQL implementation that is tested with SQLite and MySQL.`
- in lib/Mail/DMARC/Report/Store/SQL.pm, this line needs updating: `Tested with SQLite and MySQL.`
- in share/mail-dmarc.ini, this line:  `SQLite and MySQL are tested.`

**Pull request merged**
