### PR TITLE
155 delete reports

### LINKED ISSUE #155: reports are not removed from database after being successfully sent
Tested with MySQL and SQLite database with internal SMTP and smarthost on multiple systems (Jessie / Buster / Bullseye / Perl 5.20 / 5.28 / 5.30) with same result . After a 250 response the report is not cleaned from the database and is being sent over and over again when dmarc_send_report is started.

'dmarc_send_report --verbose'  output:
```
SMTP accepted
        250 OK id=1id9gb-0006hb-QB

Sending error query called by Mail::DMARC::Report::Store::SQL, 146
        DELETE FROM report_record_reason WHERE report_record_id IN (2)
         at /usr/local/share/perl/5.28.1/Mail/DMARC/Report/Store.pm line 12.
```

### PR DESCRIPTION
**Pull request by msimerson**
- fix $sql->delete_report, fixes #155 
- delete_from_where_record_in, accepts single ID or list of ids
- add test that checks to assure deleted reports truly are

### CODE REVIEW

**Comment by freddieleeman** [comment]
Nice! When can we expect it to hit metacpan.org?

**Comment by msimerson** [comment]
After someone deploys and verifies that all is well. That might be me, eventually. If you want to kick the tires, please check out master and report back.

**Comment by freddieleeman** [comment]
I would love to, but I'm unable to build the latest master using the INSTALL.md instructions. See https://github.com/msimerson/mail-dmarc/issues/159

**Comment by freddieleeman** [comment]
I've been running an testing extensively and can verify that this indeed fixes #155.

**Pull request merged**
