### PR TITLE
Optionally log to syslog when sending reports

### PR DESCRIPTION
**Pull request by marcbradshaw**
Add a --syslog option to dmarc_send_reports which logs details of report sending to syslog.

### CODE REVIEW

**Comment by msimerson** [comment]
First thought: great feature. Next thought: this is likely to get used elsewhere in Mail::DMARC. So why not put a helper function in our Base class? Something that makes it nice and easy to emit log messages all over the place, with minimal amounts of code. 

```perl
$dmarc->syslog( "this is my sample message'" );  # default LOG_INFO
$dmarc->syslog(LOG_CRIT, "the sky is falling" );

somewhere near: Mail::DMARC::syslog

sub syslog {
    if (! $some_cli_arg && ! $config_file_setting) return;
    ....
}
```

**Comment by marcbradshaw** [comment]
Have been thinking on this for a few days, I think the only other place it would be appropriate to directly syslog would be in the HTTP clients.  I wouldn't want the modules to log directly when used from Perl as this could conflict with syslog usage from the calling program.

**Comment by msimerson** [comment]
>  the only other place it would be appropriate to directly syslog would be in the HTTP clients

Fair enough.

I'd still like to see the `if`, `join`, and `LOG_INFO` stuff wrapped in a function, such that every call to syslog doesn't have to repeat that same block of code.

**Comment by marcbradshaw** [comment]
updated

**Pull request merged**
